-- Use database
CREATE DATABASE IF NOT EXISTS user DEFAULT CHARACTER SET utf8mb4 DEFAULT COLLATE utf8mb4_unicode_520_ci;
use user;

-- Set up table
CREATE TABLE IF NOT EXISTS user (
  LINE_UID varchar(33) NOT NULL,
  CREATED_DTIME timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UPDATED_DTIME timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`LINE_UID`)
);