kind: Deployment
apiVersion: apps/v1
metadata:
  name: register-web-server
  labels:
    k8s-app: register-web-server
spec:
  selector:
    matchLabels:
      k8s-app: register-web-server
  template:
    metadata:
      labels:
        k8s-app: register-web-server
        name: register-web-server
    spec:
      terminationGracePeriodSeconds: 60
      containers:
      - image: disam8853/register-web-server
        name: register-web-server
        imagePullPolicy: Always
        ports:
        - containerPort: 8000
        envFrom:
        - configMapRef:
           name: register-web-server-config