apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: api-users-ingress
spec:
  entryPoints:
    - web
  routes:
  - match: PathPrefix(`/users`) || PathPrefix(`/register`) || PathPrefix(`/docs`) || PathPrefix(`/api-docs`)
    kind: Rule
    services:
    - name: api-users
      port: 8080
