namespace: line-beta

resources:
- ../../../base/register-web
- resources/ingressroute.yaml

replicas:
- name: register-web-client
  count: 1
- name: register-web-server
  count: 1

configMapGenerator:
- name: register-web-server-config
  envs:
  - config/config.properties

secretGenerator:
- name: register-web-server-secret
  envs:
  - config/secret.properties