FROM node:16.4 AS build-stage
COPY . /app
WORKDIR /app
RUN yarn install --prod && yarn build

FROM nginx:1.15
COPY --from=build-stage /app/build/ /usr/share/nginx/html
COPY /nginx.conf /etc/nginx/conf.d/default.conf
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]