apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: webhook-ingress
spec:
  entryPoints:
    - websecure
  routes:
  - match: Path(`/callback`) && Method(`POST`)
    kind: Rule
    services:
    - name: webhook
      port: 8000
