kind: Deployment
apiVersion: apps/v1
metadata:
  name: register-web-client
  labels:
    k8s-app: register-web-client
spec:
  selector:
    matchLabels:
      k8s-app: register-web-client
  template:
    metadata:
      labels:
        k8s-app: register-web-client
        name: register-web-client
    spec:
      containers:
      - image: disam8853/register-web-client
        name: register-web-client
        imagePullPolicy: Always
        ports:
        - containerPort: 80